### ISSUE TITLE
Please clarify if -lc++ flag should be added to Project or Target

### ISSUE THREAD

**Issue by rturk** [kayla-tech/react-native-card-io#10]
Hi,
Thanks for building and sharing such amazing code.

Can you please clarify item 6 of the setup instructions?

> Add the -lc++ flag to Build Settings -> Other Linker Flags.

This needs to be included in Xcode `Project` or `Target` settings?

**Comment by rogchap** [comment]
Should not matter as if set to `Project` then the `Target` will inherit from the `Project`... But to give you an answer it: set it on the `Target`
