### ISSUE TITLE
No +[RCTConvert UIView:] function found

### ISSUE THREAD

**Issue by billdozr** [kayla-tech/react-native-card-io#12]
After install and config, when I try to do a simple call to &lt;CardIOView ... /&gt;, I get an error:

  [RCTComponentData.m:191] No +[RCTConvert UIView:] function found

against latest stable react-native build. My dependency list is

  "dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.24.1",
    "react-native-card-io": "^1.0.4"
  }

Does react-native-card-io work with RN 0.24.1 or are their known issues?

**Comment by rogchap** [comment]
`scanOverlayView={<View />}` is not working (properly never did) Just remove this line to get it working.

See #7
