### ISSUE TITLE
Upgrade to RN0.25

### ISSUE THREAD

**Issue by rturk** [kayla-tech/react-native-card-io#17]
Starting in RN 25 React Native import wil change:

Requiring React API from react-native will be deprecated:
https://github.com/facebook/react-native/releases/tag/v0.25.1

Instead of:

`import React, { Component, View } from 'react-native';
`

you should now:

```
import React, { Component } from 'react';
import { View } from 'react-native';
```

You can also try this codemod built by the community to automatically rewrite all the imports.
https://github.com/sibeliusseraphini/codemod-RN24-to-RN25

**Comment by rturk** [comment]
@rogchap Tks! Can you publish a new NPM major version?

**Comment by rogchap** [comment]
@rturk See https://github.com/kayla-tech/react-native-card-io/pull/18#issuecomment-218340272

**Comment by rogchap** [comment]
If you need to use this today you should be able to reference your dependency to Github and not the NPM Registry as I've published the latest to master:

``` json
"dependencies": {
  "react-native-card-io": "kayla-tech/react-native-card-io"
}
```

https://docs.npmjs.com/files/package.json#github-urls

**Comment by rogchap** [comment]
Finally managed to publish 1.0.5 to NPM Registry.
