### ISSUE TITLE
Can I get it to run without using cocoapods?

### ISSUE THREAD

**Issue by zeekayzeekay** [kayla-tech/react-native-card-io#19]
I have setup the react-native-card-io in my project. I have followed the setup instructions, but since this project is not using cocoapods, hence there is no .xcworkspace in my project. I opened my project in XCode using .xcodeproj and had setup the app following the rest of the instructions. Now when am using this plugin in one of the pages of my app, the card view is not getting rendered. There are no errors, the elements following and trailing the cardView element is being drawn but not the cardView element in itself.
`<View>
    <Text> Entering the block of CardIO </Text>
    <CardIOView
      languageOrLocale="en"
      guideColor="#000000"
      useCardIOLogo={true}
      hideCardIOLogo={false}
      allowFreelyRotatingCardGuide={true}
      scanInstructions={'Hold card here. It will scan automatically.'}
      scanExpiry={true}
      scannedImageDuration={2}
      hidden={false}
      detectionMode={CardIOView.automatic}
      didScanCard={result => console.log(result)} />
    <Text> Exiting the block of CardIO </Text>
  </View>
`
Is it possible that due to not setting it up through .xcworkspace, there is this problem regarding rendering the cardView block?

**Comment by rogchap** [comment]
Did you re-build the app after you installed? Is there any errors in the XCode console?
Also make sure that the libCardIO.a unzipped correctly during npm install.
Should work without Cocoapods.

**Comment by zeekayzeekay** [comment]
Thanks @rogchap , the issue that I was facing was actually the video block was being positioned out of the viewport by default, and I couldn't detect it. It is working fine without cocoapods.
