### ISSUE TITLE
Not working / Crashing

### ISSUE THREAD

**Issue by brunolemos** [kayla-tech/react-native-card-io#21]
Trying to run the most basic example, but the app crashes.
It tries to render the component, shows the gray background with the paypal logo, and that's it, it crashes.

```
import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, View, Navigator, TouchableHighlight } from 'react-native';

import { CardIOView } from 'react-native-card-io';

export default class Pay extends Component {
  render() {
    return (
      <CardIOView style={{ flex: 1 }} />
    );
  }
}
```

The Xcode debugger does not provide any useful error.

```
libsystem_kernel.dylib`__abort_with_payload:
    0x182570d94 <+0>:  movz   x16, #0x209
    0x182570d98 <+4>:  svc    #0x80
->  0x182570d9c <+8>:  b.lo   0x182570db4               ; <+32>
    0x182570da0 <+12>: stp    x29, x30, [sp, #-16]!
    0x182570da4 <+16>: mov    x29, sp
    0x182570da8 <+20>: bl     0x1825557dc               ; cerror_nocancel
    0x182570dac <+24>: mov    sp, x29
    0x182570db0 <+28>: ldp    x29, x30, [sp], #16
    0x182570db4 <+32>: ret    
```

Tried on OS X 10.11 and macOS Sierra 10.12.
Tried on iPhone 5S (iOS 9) and on iPhone 6S (iOS 10).

**Comment by rogchap** [comment]
Hmmm... seems like it's crashing when initializing the camera.
When you say you've tried on iPhone 5S etc, do you mean the physical device or the simulator?
Camera won't work on the simulator.

**Comment by brunolemos** [comment]
Physical device. 

I got it working just a few minutes ago but not using this repo, by creating a new bridge from "scratch" (copying some parts of the source code of BBB/react-native-card.io).

**Comment by rogchap** [comment]
We might need to update the version of react-native or even the Card.IO lib.
Which version of RN are you using?

**Comment by brunolemos** [comment]
The latest of everything.

```
react 15.2.1
react-native 0.31.0
card-io 5.3.2
```

**Comment by rogchap** [comment]
Are you using you're own version of `card-io` lib?
I think our version of card.io is at 5.2.0; This package installs a version of card.io without you needing to (via pods etc).
You may have two versions of the lib running, but if not could explain the error above.

**Comment by brunolemos** [comment]
Sorry, I meant that I used the version 5.3.2 in the new bridge I created to get it working.

I believe that updating the packages and relinking the libraries / readding the frameworks will be enough to fix it 👍
