### ISSUE TITLE
I was white screen error?

### ISSUE THREAD

**Issue by khanhdd83** [kayla-tech/react-native-card-io#23]
<img width="384" alt="screen shot 2016-09-28 at 15 42 27" src="https://cloud.githubusercontent.com/assets/7984350/18906564/3af46278-8592-11e6-948f-fcb18f6a4fc3.png">

**Comment by rogchap** [comment]
Can't see your error. Have you installed correctly correctly? Have you set your `flexbox` to the correct value for the view?
