### ISSUE TITLE
didScanCard not triggering

### ISSUE THREAD

**Issue by cmmouritsen** [kayla-tech/react-native-card-io#3]
I'm not 100% positive this is a problem with this library or when this problem started, but in React Native 0.19 the didScanCard event never triggers for me on the javascript side. I have debugged on the native iOS side and I see the event get called there, but it never hits my javascript listener. I wondered if something has changed in how native modules should trigger events.

**Comment by rogchap** [comment]
From the top of my head, I think the React Native team have changed how events get fired back from Obj-C to JavaScript... Will take a look to see what the issue is... Feel free to submit any PR if you discover the issue.

**Comment by cmmouritsen** [comment]
Pull request submitted.

**Comment by rogchap** [comment]
https://github.com/kayla-tech/react-native-card-io/pull/4
