### ISSUE TITLE
Unable to see  Card Scanning view - "No +[RCTConvert UIView:] function found".

### ISSUE THREAD

**Issue by danginirav** [kayla-tech/react-native-card-io#7]
I have followed exactly the same steps/instructions mentioned in readme file but still it's not working.
Unable to see Card Scanning view. Getting "**No +[RCTConvert UIView:] function found**" error. I am using **iPad Air 2** device. See the attached image for more details.
![img_20160413_152713036](https://cloud.githubusercontent.com/assets/5415342/14489948/8ffb83e8-018d-11e6-9d18-b7f75ab94895.jpg)

**Comment by rogchap** [comment]
What version of RN are you using?
Hard to debug this with just a screenshot of the Redbox. Can you provide an example app that causes this?

**Comment by danginirav** [comment]
@rogchap 
It worked after removing the `scanOverlayView={<View />}`.
It's silly or maybe I am not knowing how to use this property.

Thank you!
