### ISSUE TITLE
Card-io render issue

### ISSUE THREAD

**Issue by alexleventer** [kayla-tech/react-native-card-io#8]
I'm getting the following error in my RCTComponentData.m file when I try to render the component:  `(typeSignature.methodReturnType[0]) {` `Thread 1` `EXC_BAD_ACCESS (code=1, address=0x0)`

**Comment by rogchap** [comment]
`EXC_BAD_ACCESS` could literally be anything! It's one of those horrible Obj-C errors that is a catch-all error. 
Are you sure this error is coming from this RN component? Do you have an example repo that I can take a look at that throws this error?

**Comment by rogchap** [comment]
Closing due to no response. Please re-open if you feel this is still an issue.
